-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 09:49:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zoonosis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zoonosis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoonosis` DEFAULT CHARACTER SET utf8 ;
USE `zoonosis` ;

-- -----------------------------------------------------
-- Table `zoonosis`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoonosis`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` VARCHAR(100) NULL,
  `correo` VARCHAR(50) NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoonosis`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoonosis`.`mascotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `a_codigo` VARCHAR(45) NULL,
  `a_fecha` DATE NULL,
  `a_propietario` VARCHAR(60) NULL,
  `a_zona` VARCHAR(100) NULL,
  `a_latitud` VARCHAR(45) NULL,
  `a_longitud` VARCHAR(45) NULL,
  `a_motivo` VARCHAR(45) NULL,
  `a_motivo_otro` VARCHAR(45) NULL,
  `b_imagen` VARCHAR(50) NULL,
  `b_nombre` VARCHAR(45) NULL,
  `b_raza` VARCHAR(45) NULL,
  `b_color` VARCHAR(45) NULL,
  `b_especie` VARCHAR(45) NULL,
  `b_sexo` VARCHAR(45) NULL,
  `c_estado_animal` VARCHAR(45) NULL,
  `c_observacion` TEXT NULL,
  `e_nombre` VARCHAR(60) NULL,
  `e_fecha` DATE NULL,
  `f_nombre` VARCHAR(60) NULL,
  `f_fecha` DATE NULL,
  `f_fecha_dos` DATE NULL,
  `g_carnet` VARCHAR(10) NULL,
  `g_fecha_vcr` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
